name: Scrapy Crawl - Worldometers - Countries

on:
  push:
    branches: [ main ]

jobs:
  Scrapy-Crawl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Install Python 3.8.16
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.16

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scrapy autopep8 pylint

    - name: Crawl
      run: |
        cd worldometers/
        scrapy crawl countries
