name: Scrapy Checks - Worldometers - Countries

on:
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Install Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Scrapy Check
      run: |
        cd worldometers/
        scrapy check --verbose
